# Generated by Django 3.2.25 on 2024-11-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ja_item', models.CharField(max_length=255)),
                ('en_item', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('no', models.IntegerField()),
                ('abilities', models.JSONField()),
                ('types', models.JSONField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('evolutions', models.JSONField(blank=True, null=True)),
                ('level_up_moves', models.JSONField(blank=True, null=True)),
                ('tms', models.JSONField(blank=True, null=True)),
                ('trs', models.JSONField(blank=True, null=True)),
                ('egg_moves', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
